all:
	
	gcc main.c View/HotelView.c Controller/hotelController.c View/hospedeView.c Controller/hospedeController.c View/categoriaAcomodacoesView.c Controller/categoriaAcomodacaoController.c View/acomodacoesView.c Controller/acomodacaoController.c View/fornecedoresView.c Controller/fornecedoresController.c View/produtosView.c Controller/produtosController.c View/reservaView.c Controller/reservaController.c View/checkInView.c Controller/checkInController.c View/controleDeCaixaView.c Controller/controleDeCaixaController.c View/OperadoresDoSistemaView.c Controller/OperadoresDoSistemaController.c View/saidaProdutosView.c Controller/saidaProdutosController.c View/importacaoExportacaoView.c View/transacoesView.c -o programa

clean:

	rm *.o