all:

	gcc main.c Controller/basicoController.c View/HotelView.c Controller/hotelController.c View/hospedeView.c Controller/hospedeController.c View/saidaProdutosView.c View/categoriaAcomodacaoView.c Controller/categoriaAcomodacaoController.c View/acomodacoesView.c Controller/acomodacoesController.c View/fornecedoresView.c Controller/fornecedoresController.c View/produtosView.c Controller/produtosController.c View/reservaView.c Controller/reservaController.c View/checkInView.c Controller/checkInController.c View/controleDeCaixaView.c Controller/controleDeCaixaController.c View/OperadoresDoSistemaView.c Controller/OperadoresDoSistemaController.c  Controller/saidaProdutosController.c View/importacaoExportacaoView.c View/transacoesView.c View/checkOutView.c Controller/checkOutController.c -o programa

clean:

	rm *.o
